//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbbuku.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BukuEntities : DbContext
    {
        public BukuEntities()
            : base("name=BukuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<tblM_Buku> tblM_Buku { get; set; }
        public virtual DbSet<TblM_Transaksi> TblM_Transaksi { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
