//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbbuku.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblM_Transaksi
    {
        public int ID { get; set; }
        public int BukuId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> Jumlah { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
